//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_category
    {
        public long id { get; set; }
        public long parent_id { get; set; }
        public string category_name { get; set; }
        public byte domain { get; set; }
        public long category_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual @object @object { get; set; }
    }
}
