//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public long id { get; set; }
        public long category_id { get; set; }
        public long sub_category_id { get; set; }
        public Nullable<long> object_id { get; set; }
        public long event_id { get; set; }
        public int score { get; set; }
        public long user_id { get; set; }
        public byte domain { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
        public long event_id1 { get; set; }
        public long user_profile_id { get; set; }
        public string user_profileUserID { get; set; }
        public string user_profile_email { get; set; }
        public long user_profile_sub_category_id { get; set; }
        public byte user_profile_moderator { get; set; }
    
        public virtual @event @event { get; set; }
        public virtual user_profile user_profile { get; set; }
    }
}
