//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class xscoreEntities2 : DbContext
    {
        public xscoreEntities2()
            : base("name=xscoreEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<@object> objects { get; set; }
        public virtual DbSet<sub_category> sub_category { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<user_profile> user_profile { get; set; }
    
        public virtual int sp_get_categories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_get_categories");
        }
    
        public virtual int sp_get_events()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_get_events");
        }
    
        public virtual int sp_get_objects()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_get_objects");
        }
    
        public virtual ObjectResult<Nullable<long>> sp_get_profile_id(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("sp_get_profile_id", emailParameter);
        }
    
        public virtual int sp_get_rating_level(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_get_rating_level", idParameter);
        }
    
        public virtual int sp_insert_transactions(Nullable<long> user_id, Nullable<long> category_id, Nullable<long> sub_category_id, Nullable<long> object_id, Nullable<long> event_id, Nullable<int> score, Nullable<byte> domain)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(long));
    
            var category_idParameter = category_id.HasValue ?
                new ObjectParameter("category_id", category_id) :
                new ObjectParameter("category_id", typeof(long));
    
            var sub_category_idParameter = sub_category_id.HasValue ?
                new ObjectParameter("sub_category_id", sub_category_id) :
                new ObjectParameter("sub_category_id", typeof(long));
    
            var object_idParameter = object_id.HasValue ?
                new ObjectParameter("object_id", object_id) :
                new ObjectParameter("object_id", typeof(long));
    
            var event_idParameter = event_id.HasValue ?
                new ObjectParameter("event_id", event_id) :
                new ObjectParameter("event_id", typeof(long));
    
            var scoreParameter = score.HasValue ?
                new ObjectParameter("score", score) :
                new ObjectParameter("score", typeof(int));
    
            var domainParameter = domain.HasValue ?
                new ObjectParameter("domain", domain) :
                new ObjectParameter("domain", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_transactions", user_idParameter, category_idParameter, sub_category_idParameter, object_idParameter, event_idParameter, scoreParameter, domainParameter);
        }
    
        public virtual int sp_insert_user_profile(string userId, string email, Nullable<long> sub_category_id, Nullable<byte> moderator)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var sub_category_idParameter = sub_category_id.HasValue ?
                new ObjectParameter("sub_category_id", sub_category_id) :
                new ObjectParameter("sub_category_id", typeof(long));
    
            var moderatorParameter = moderator.HasValue ?
                new ObjectParameter("moderator", moderator) :
                new ObjectParameter("moderator", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_user_profile", userIdParameter, emailParameter, sub_category_idParameter, moderatorParameter);
        }
    
        public virtual int sp_report_get_object_overall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_report_get_object_overall");
        }
    }
}
