//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Web.Mvc;

    public partial class transactionView
    {
        public long id { get; set; }
        public string category_name { get; set; }
        public long category_id { get; set; }

        public IQueryable<SelectListItem> categories { get; set; }
        public long sub_category_id { get; set; }
        public string object_name { get; set; }

        public IQueryable<SelectListItem> objects { get; set; }
        public long ?object_id { get; set; }
        public string events_name { get; set; }
        public long events_id { get; set; }

        public IQueryable<SelectListItem> events { get; set; }
        public int score { get; set; }
        public long user_profile_id { get; set; }
        public byte domain { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
        public virtual DbSet<transactionView> transactions { get; set; }

        public IQueryable<SelectListItem> GetCategories(xscoreEntities2 idb, category e)
        {
            var a = new List<SelectListItem>();
            a = idb.categories.Select(u => new SelectListItem { Text = u.category_name, Value = u.categories_id.ToString() }).ToList();
            a.Insert(0, new SelectListItem { Value = e.categories_id.ToString(), Text = e.category_name });
            return a.AsQueryable();
        }
        public IQueryable<SelectListItem> GetObjects(xscoreEntities2 idb, @object e)
        {
            List<SelectListItem> a = new List<SelectListItem>();
            a = idb.objects.Select(u => new SelectListItem { Text = u.object_name, Value = u.object_id.ToString() }).ToList();
            a.Insert(0, new SelectListItem { Value = e.object_id.ToString(), Text = e.object_name });
            return a.AsQueryable();
        }
        public IQueryable<SelectListItem> GetEvents(xscoreEntities2 idb, @event e)
        {
            List<SelectListItem> a = new List<SelectListItem>();
            a = idb.events.Select(u => new SelectListItem { Text = u.event_name, Value = u.event_id.ToString() }).ToList();
            a.Insert(0, new SelectListItem { Value = e.event_id.ToString(), Text = e.event_name });
            return a.AsQueryable();
        }
    }


}
