//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public long id { get; set; }
        public long categories_id { get; set; }
        public long sub_category_id { get; set; }
        public Nullable<long> object_id { get; set; }
        public long events_id { get; set; }
        public int score { get; set; }
        public long user_profile_id { get; set; }
        public byte domain { get; set; }
        public Nullable<System.DateTime> time_stamp { get; set; }
    }
}
