//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_profile
    {
        public long id { get; set; }
        public string UserID { get; set; }
        public string email { get; set; }
        public long sub_category_id { get; set; }
        public byte moderator { get; set; }
    }
}
